### PR TITLE
Autopkg formatting

### PR DESCRIPTION
**Pull request by grahampugh**
This branch does extended formatting of AutoPkg yaml recipes. In addition to the initial reformatting provided by @homebysix, this:

- Ensures Process dictionaries are in the order Processor, Comment, Arguments.
- Ensures the NAME tuple is the first item in the Index dictionary.
- Ensures the order of the recipe items is Comment, Description, Identifier, ParentRecipe, MinimumOSVersion, Input, Process.
- Adds spaces above the Input and Process dictionaries, and between Process items.

### CODE REVIEW

**Comment by grahampugh** [comment]
Here is an example:

```yaml
Description: Downloads the latest version of KNIME.
Identifier: com.github.grahampugh.download.KNIME
MinimumVersion: 1.0.0

Input:
  NAME: KNIME
  DOWNLOAD_URL: https://download.knime.org/analytics-platform/macosx/knime-latest-app.macosx.cocoa.x86_64.dmg
  STOPPROCESSINGIF_PREDICATE: download_changed == FALSE

Process:
- Processor: URLDownloader
  Arguments:
    filename: '%NAME%.dmg'
    url: '%DOWNLOAD_URL%'

- Processor: EndOfCheckPhase

- Processor: StopProcessingIf
  Arguments:
    predicate: '%STOPPROCESSINGIF_PREDICATE%'

- Processor: CodeSignatureVerifier
  Arguments:
    input_path: '%pathname%/KNIME*.app'
    requirement: identifier "org.knime.product" and anchor apple generic and certificate 1[field.1.2.840.113635.100.6.2.6] /* exists */ and certificate leaf[field.1.2.840.113635.100.6.1.13] /* exists */ and certificate leaf[subject.OU] = V7WZJX2HS9

- Processor: Copier
  Arguments:
    destination_path: '%RECIPE_CACHE_DIR%/downloads/KNIME.app'
    source_path: '%pathname%/KNIME*.app'

- Processor: Versioner
  Arguments:
    input_plist_path: '%destination_path%/Contents/Info.plist'
    plist_version_key: CFBundleShortVersionString

- Processor: PathDeleter
  Arguments:
    path_list:
    - '%RECIPE_CACHE_DIR%/downloads/KNIME.app'
```

**Comment by grahampugh** [comment]
I will add a function to batch tidy up existing .recipe.yaml files using the new functions shortly.

**Comment by homebysix** [comment]
I've got an idea to force MinimumVersion and other version-like items into quoted strings, but probably need to wait until this PR is merged to avoid conflicts.

**Comment by grahampugh** [comment]
I'll try and get this merged sometime today, though it got a bit messy trying to be clever with batch conversions, which are probably too dangerous anyway. so I might roll it back slightly.

**Comment by grahampugh** [comment]
@homebysix I'm going to admit, I don't like what I'm doing much here. I really wanted to enforce strings to literal scalars as this is basically essential for readable yaml recipes containing scripts and multiline strings. Example:

Quoted string:
```yaml
  Processor: FileCreator
- Arguments:
    file_content: "#!/bin/bash\n\nDIR=$(dirname \"$0\")\n\n$DIR/COMSOL.app/Contents/Resources/setup -s $DIR/setupconfig.ini\n"
    file_mode: '0755'
    file_path: '%RECIPE_CACHE_DIR%/Scripts/postinstall'
```

Literal scalar:
```yaml
- Processor: FileCreator
  Arguments:
    file_content: |
      #!/bin/bash
      
      DIR=$(dirname "$0")
      
      $DIR/COMSOL.app/Contents/Resources/setup -s $DIR/setupconfig.ini
    file_mode: '0755'
    file_path: '%RECIPE_CACHE_DIR%/Scripts/postinstall'
```

I tried various methods to achieve this using ruamel.yaml's new API, but it always ended up with a mess of extra code in the yaml which we definitely don't want. So, I hacked it with just string substitution, which is obviously fragile. That said, I've converted various recipes and haven't seen an error yet.

Another thing that remains is whether we need to quote strings that have `%autopkgVariables%` in them. It seems unnecessary as far as AutoPkg is concerned, but `yaml-plist.py` won't convert those files.

I think I'll merge this anyway, but with the caveat that it's _dirty horrible code_, so I will immediately create issues to fix that up.

**Comment by grahampugh** [comment]
Oh and another thing is that the AutoPkg prettifying only happens with python3, so you have to ensure that plistyamlplist is run using python3.

**Pull request merged**
